loglevel : debug

logfile : log.txt

database_url:
    device: db.sqlite

template_files:
    applications: examples/humanitas/applications.json
    devices: examples/humanitas/devices.json

device_positionning:
    x_min: 0
    x_max: 40
    y_min: 0
    y_max: 40
    z_min: 0
    z_max: 30

application_number : 5000

device_number : 109

wifi_range : 6

app_duration : 0