loglevel : info

#logfile : latest/log.txt

database_url:
    device: db.sqlite

#template_files:
#    applications: latest/applications.json
#    devices: latest/devices.json

device_positioning:
    x_min: 0
    x_max: 40
    y_min: 0
    y_max: 40
    z_min: 0
    z_max: 30

application_number : 8700
device_number : 200
wifi_range : 6
app_duration : 0
k_param : 10
seed : 12345