loglevel : info

logfile : log.txt

database_url:
    device: db.sqlite

device_positionning:
    x_min: 0
    x_max: 40
    y_min: 0
    y_max: 40
    z_min: 0
    z_max: 30

application_number : 500

device_number : 100

wifi_range : 6