loglevel : info

logfile : latest/log.txt

database_url:
    device: db.sqlite

template_files:
    applications: input/applications/1-applications.json
    devices: input/devices/1-random5050/devices.json

device_positionning:
    x_min: 0
    x_max: 40
    y_min: 0
    y_max: 40
    z_min: 0
    z_max: 30

application_number : 8000

device_number : 200

wifi_range : 6

app_duration : 0